=== argouml-tigris-org/argouml/maurelio1234/argouml/argouml/persistence/registry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 beta 3 build Dec 21 2000 (http://www.xmlspy.com) by Curt Arnold (Self) -->
<xsd:schema targetNamespace="http://www.argouml.org/Namespace/0.9/Registry" xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" xmlns="http://www.argouml.org/Namespace/0.9/Registry" elementFormDefault="qualified">
	<xsd:simpleType name="package">
		<xsd:annotation>
			<xsd:documentation>The type represents a Java package name, such as "java.lang" or "org.argouml.critiques".</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:simpleType name="class">
		<xsd:annotation>
			<xsd:documentation>The type represents a Java class name, such as "java.lang.Double".</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:simpleType name="pixels">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="MetaClassEnum">
		<xsd:annotation>
			<xsd:documentation>Enumeration of metaclasses that can have associated FigShape's</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Class"/>
			<xsd:enumeration value="Interface"/>
			<xsd:enumeration value="Classifier"/>
			<xsd:enumeration value="ModelElement"/>
			<xsd:enumeration value="Attribute"/>
			<xsd:enumeration value="Actor"/>
			<xsd:enumeration value="Stimulus"/>
			<xsd:enumeration value="Object"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="Registry">
		<xsd:annotation>
			<xsd:documentation>A registry of configuration settings for ArgoUML</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:element ref="UMLProfile"/>
					<xsd:element ref="Frame"/>
					<xsd:choice minOccurs="0" maxOccurs="unbounded">
						<xsd:element ref="Critique"/>
						<xsd:element ref="CritiqueGroup"/>
						<xsd:element ref="CodeGenerator"/>
						<xsd:element ref="CodeAnalyzer"/>
						<xsd:element ref="ReportGenerator"/>
						<xsd:element ref="Notation"/>
						<xsd:element ref="FileImport"/>
						<xsd:element ref="FileExport"/>
					</xsd:choice>
				</xsd:choice>
				<xsd:element ref="Personality" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="version" type="xsd:string"/>
			<xsd:attribute name="defaultPackage" type="package"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="UMLProfile">
		<xsd:annotation>
			<xsd:documentation/>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="TagName"/>
				<xsd:element ref="FigShape"/>
				<!--  this is temporary until UML 1.4  -->
			</xsd:choice>
			<xsd:attribute name="id" type="xsd:ID" use="required"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="href" type="xsd:uriReference"/>
			<xsd:attribute name="description" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="TagName">
		<xsd:annotation>
			<xsd:documentation>Represents a predefined tag name known in this profile, will be deprecated with UML 1.4.  Content of element is description of tag name.</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="name" type="xsd:string" use="required"/>
					<xsd:attribute name="baseClass" type="xsd:string" use="default" value="ModelElement"/>
					<xsd:attribute name="validationClass" type="class" use="default" value="java.lang.String"/>
					<xsd:attribute name="stereotype" type="xsd:string"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="FigShape">
		<xsd:annotation>
			<xsd:documentation>Registers a class that can provide a different graphical representation</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="name" type="xsd:string" use="required"/>
					<xsd:attribute name="renderer" type="class" use="required"/>
					<xsd:attribute name="baseClass" type="xsd:string" use="default" value="Class"/>
					<xsd:attribute name="stereotype" type="xsd:string"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Frame">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element ref="Pane"/>
			</xsd:choice>
			<xsd:attribute name="id" type="xsd:ID" use="required"/>
			<xsd:attribute name="height" type="pixels"/>
			<xsd:attribute name="width" type="pixels"/>
			<xsd:attribute name="defaultPackage" type="package"/>
			<xsd:attribute name="class" type="class"/>
			<xsd:attribute name="title" type="xsd:string"/>
			<xsd:attribute name="theme" type="class"/>
			<xsd:attribute name="notation" type="xsd:IDREF"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Pane">
		<xsd:complexType>
			<xsd:choice minOccurs="0">
				<xsd:element name="TabbedPane"/>
				<xsd:element name="SplitPane"/>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string"/>
			<xsd:attribute name="height" type="pixels"/>
			<xsd:attribute name="width" type="pixels"/>
			<xsd:attribute name="gridheight" type="xsd:integer"/>
			<xsd:attribute name="gridwidth" type="xsd:integer"/>
			<xsd:attribute name="gridx" type="xsd:integer"/>
			<xsd:attribute name="gridy" type="xsd:integer"/>
			<xsd:attribute name="weightx" type="xsd:double"/>
			<xsd:attribute name="weighty" type="xsd:double"/>
			<xsd:attribute name="class" type="class"/>
			<xsd:attribute name="defaultPackage" type="package"/>
			<xsd:attribute name="notation" type="xsd:IDREF"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="TabbedPane">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="Tab"/>
			</xsd:sequence>
			<xsd:attribute name="notation" type="xsd:IDREF"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="SplitPane">
		<xsd:complexType>
			<xsd:attribute name="dividerSize" type="pixels" use="required"/>
			<xsd:attribute name="dividerLocation" type="xsd:integer" use="required"/>
			<xsd:attribute name="isHorizontal" type="xsd:boolean" use="default" value="false"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Tab">
		<xsd:complexType>
			<xsd:attribute name="class" type="class" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="Behavior">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="description" type="xsd:string"/>
		<xsd:attribute name="isEnabled" type="xsd:boolean" use="default" value="true"/>
		<xsd:attribute name="id" type="xsd:ID" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="JavaBehavior">
		<xsd:complexContent>
			<xsd:extension base="Behavior">
				<xsd:attribute name="class" type="class" use="required"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="TemplateBehavior">
		<xsd:complexContent>
			<xsd:extension base="JavaBehavior">
				<xsd:attribute name="template" type="xsd:uriReference"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="CodeGenerator" type="TemplateBehavior"/>
	<xsd:element name="Notation" type="JavaBehavior"/>
	<xsd:element name="CodeAnalyzer" type="JavaBehavior"/>
	<xsd:element name="ReportGenerator" type="TemplateBehavior"/>
	<xsd:element name="FileImport" type="JavaBehavior"/>
	<xsd:element name="FileExport" type="TemplateBehavior"/>
	<xsd:element name="CritiqueGroup">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="Behavior">
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element ref="Critique"/>
					</xsd:sequence>
					<xsd:attribute name="defaultPackage" type="package"/>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Critique">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string"/>
			<xsd:attribute name="description" type="xsd:string"/>
			<xsd:attribute name="isEnabled" type="xsd:boolean" use="default" value="true"/>
			<xsd:attribute name="class" type="class" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Personality">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="description" type="xsd:string" use="optional"/>
			<xsd:attribute name="isDefault" type="xsd:boolean" use="default" value="false"/>
			<xsd:attribute name="frame" type="xsd:IDREF" use="required"/>
			<xsd:attribute name="profiles" type="xsd:IDREFS" use="required"/>
			<xsd:attribute name="behaviors" type="xsd:IDREFS"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== argouml-tigris-org/argouml/maurelio1234/argouml/argouml/registry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 beta 3 build Dec 21 2000 (http://www.xmlspy.com) by Curt Arnold (Self) -->
<Registry xmlns="http://www.argouml.org/Namespace/0.9/Registry" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:schemaLocation="http://www.argouml.org/Namespace/0.9/Registry
xml\dtd\registry.xsd">
	<UMLProfile id="profile1" name="default.xmi">
		<TagName name="fred" baseClass="ModelElement"/>
		<FigShape name="BoundaryShape" renderer="org.example.ArgoUML.shapes.BoundaryShape" stereotype="Boundary" baseClass="Class"/>
	</UMLProfile>
	<CritiqueGroup name="UML Critiques" id="UMLCritiques" defaultPackage="org.argouml.uml.cognitive.critics">
		<Critique class="CrAlreadyRealizes"/>
		<Critique class="CrAssocNameConflict"/>
		<Critique class="CrAttrNameConflict"/>
		<Critique class="CrCallWithoutReturn"/>
		<Critique class="CrCircularAssocClass"/>
		<Critique class="CrCircularComposition"/>
		<Critique class="CrCircularInheritance"/>
		<Critique class="CrClassMustBeAbstract"/>
		<Critique class="CrClassWithoutComponent"/>
		<Critique class="CrCompInstanceWithoutNode"/>
		<Critique class="CrComponentInstanceWithoutClassifier"/>
		<Critique class="CrComponentWithoutNode"/>
		<Critique class="CrConflictingComposites"/>
		<Critique class="CrConstructorNeeded"/>
		<Critique class="CrCrossNamespaceAssoc"/>
		<Critique class="CrDisambigClassName"/>
		<Critique class="CrDisambigStateName"/>
		<Critique class="CrDupParamName"/>
		<Critique class="CrDupRoleNames"/>
		<Critique class="CrEmptyPackage"/>
		<Critique class="CrFinalSubclassed"/>
		<Critique class="CrIllegalGeneralization"/>
		<Critique class="CrIllegalName"/>
		<Critique class="CrInstanceWithoutClassifier"/>
		<Critique class="CrInterfaceAllPublic"/>
		<Critique class="CrInterfaceOperOnly"/>
		<Critique class="CrInterfaceWithoutComponent"/>
		<Critique class="CrInvalidBranch"/>
		<Critique class="CrInvalidFork"/>
		<Critique class="CrInvalidInitial"/>
		<Critique class="CrInvalidJoin"/>
		<Critique class="CrLinkWithoutStimulus"/>
		<Critique class="CrMergeClasses"/>
		<Critique class="CrMissingAttrName"/>
		<Critique class="CrMissingClassName"/>
		<Critique class="CrMissingOperName"/>
		<Critique class="CrMissingStateName"/>
		<Critique class="CrMultiComposite"/>
		<Critique class="CrMultipleAgg"/>
		<Critique class="CrMultipleInitialStates"/>
		<Critique class="CrNameConflict"/>
		<Critique class="CrNameConflictAC"/>
		<Critique class="CrNameConfusion"/>
		<Critique class="CrNavFromInterface"/>
		<Critique class="CrNoAssociations"/>
		<Critique class="CrNodeInsideElement"/>
		<Critique class="CrNodeInstanceInsideElement"/>
		<Critique class="CrNodeInstanceWithoutClassifier"/>
		<Critique class="CrNoGuard"/>
		<Critique class="CrNoIncomingTransitions"/>
		<Critique class="CrNoInitialState"/>
		<Critique class="CrNoInstanceVariables"/>
		<Critique class="CrNonAggDataType"/>
		<Critique class="CrNoOperations"/>
		<Critique class="CrNoOutgoingTransitions"/>
		<Critique class="CrNoTransitions"/>
		<Critique class="CrNoTriggerOrGuard"/>
		<Critique class="CrNWayAgg"/>
		<Critique class="CrObjectWithoutClassifier"/>
		<Critique class="CrObjectWithoutComponent"/>
		<Critique class="CrOperNameConflict"/>
		<Critique class="CrOppEndConflict"/>
		<Critique class="CrOppEndVsAttr"/>
		<Critique class="CrReservedName"/>
		<Critique class="CrReturnWithoutCall"/>
		<Critique class="CrSeqInstanceWithoutClassifier"/>
		<Critique class="CrSignatureConflict"/>
		<Critique class="CrStimulusWithWrongPosition"/>
		<Critique class="CrSubclassReference"/>
		<Critique class="CrTooManyAssoc"/>
		<Critique class="CrTooManyAttr"/>
		<Critique class="CrTooManyClasses"/>
		<Critique class="CrTooManyOper"/>
		<Critique class="CrTooManyStates"/>
		<Critique class="CrTooManyTransitions"/>
		<Critique class="CrUnconventionalAttrName"/>
		<Critique class="CrUnconventionalClassName"/>
		<Critique class="CrUnconventionalOperName"/>
		<Critique class="CrUnconventionalPackName"/>
		<Critique class="CrUnnavigableAssoc"/>
		<Critique class="CrUselessAbstract"/>
		<Critique class="CrUselessInterface"/>
		<Critique class="CrUtilityViolated"/>
		<Critique class="CrWrongDepEnds"/>
		<Critique class="CrWrongLinkEnds"/>
		<Critique class="CrAlreadyRealizes"/>
		<Critique class="CrAssocNameConflict"/>
	</CritiqueGroup>
	<CritiqueGroup name="Java Critiques" id="JavaCritiques" defaultPackage="org.argouml.language.java.cognitive.critics">
		<Critique class="CrMultipleInheritance"/>
	</CritiqueGroup>
	<CodeGenerator name="JavaGen" id="JavaGen" class="org,example.CodeGenerators.JavaGen"/>
	<CodeAnalyzer name="JavaRE" id="JavaRE" class="org.example.CodeGenerators.JavaRE" description="Sample Java Code Reverse engineering"/>
	<Notation name="UML Notation" id="umlNotation" class="org.argouml.Notations.UMLNotation" description="Textual notation per UML spec"/>
	<Frame id="bigFrame" height="900" width="700" title="ArgoUML" notation="umlNotation" class="org.argouml.application.MainFrame" theme="org.argouml.themes.JasonTheme" defaultPackage="org.argouml.application">
		<Pane/>
		<Pane/>
		<Pane defaultPackage="org.argouml.uml.ui">
			<TabbedPane>
				<Tab class="org.argouml.cognitive.ui.TabToDo"/>
				<Tab class="TabProps"/>
				<Tab class="TabDocumentation"/>
				<Tab class="TabStyle"/>
				<Tab class="TabDocs"/>
				<Tab class="TabSrc"/>
				<Tab class="TabConstraints"/>
				<Tab class="TabTaggedValues"/>
				<Tab class="org.argouml.cognitive.checklist.ui.TabCheckList"/>
				<Tab class="History"/>
				<Tab class="TabHash"/>
			</TabbedPane>
		</Pane>
	</Frame>
	<Personality name="JavaPersonality" frame="bigFrame" profiles="profile1" isDefault="false" description="Default Java profile" behaviors="JavaGen JavaRE UMLCritiques JavaCritiques"/>
</Registry>
